/**
 * OptHub REST API
 * OptHub Public REST API.
 *
 * The version of the OpenAPI document: 0.3.0
 * Contact: competition@opthub.ai
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.21.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "opthub_api_client/model/AuthErrorCode.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

namespace
{
using EnumUnderlyingType = utility::string_t;

AuthErrorCode::eAuthErrorCode toEnum(const EnumUnderlyingType& val)
{
    if (val == utility::conversions::to_string_t(_XPLATSTR("APIKeyMissing")))
        return AuthErrorCode::eAuthErrorCode::APIKEYMISSING;
    if (val == utility::conversions::to_string_t(_XPLATSTR("InvalidAPIKey")))
        return AuthErrorCode::eAuthErrorCode::INVALIDAPIKEY;
    return {};
}

EnumUnderlyingType fromEnum(AuthErrorCode::eAuthErrorCode e)
{
    switch (e)
    {
    case AuthErrorCode::eAuthErrorCode::APIKEYMISSING:
        return _XPLATSTR("APIKeyMissing");
    case AuthErrorCode::eAuthErrorCode::INVALIDAPIKEY:
        return _XPLATSTR("InvalidAPIKey");
    default:
        break;
    }
    return {};
}
}

AuthErrorCode::AuthErrorCode()
{
}

AuthErrorCode::~AuthErrorCode()
{
}

void AuthErrorCode::validate()
{
    // TODO: implement validation
}

web::json::value AuthErrorCode::toJson() const
{
    auto val = fromEnum(m_value);
    return web::json::value(val);
}

bool AuthErrorCode::fromJson(const web::json::value& val)
{
    m_value = toEnum(val.as_string());
    return true;
}

void AuthErrorCode::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if (!namePrefix.empty() && namePrefix.back() != _XPLATSTR('.'))
    {
        namePrefix.push_back(_XPLATSTR('.'));
    }

    auto e = fromEnum(m_value);
    multipart->add(ModelBase::toHttpContent(namePrefix, e));
}

bool AuthErrorCode::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if (!namePrefix.empty() && namePrefix.back() != _XPLATSTR('.'))
    {
        namePrefix.push_back(_XPLATSTR('.'));
    }
    {
        EnumUnderlyingType e;
        ok = ModelBase::fromHttpContent(multipart->getContent(namePrefix), e);
        if (ok)
        {
            auto v = toEnum(e);
            setValue(v);
        }
    }
    return ok;
}

AuthErrorCode::eAuthErrorCode AuthErrorCode::getValue() const
{
   return m_value;
}

void AuthErrorCode::setValue(AuthErrorCode::eAuthErrorCode const value)
{
   m_value = value;
}

AuthErrorCode::AuthErrorCode(utility::string_t str){
    setValue( strToEnumMap[str] );
}

}
}
}
}


