/**
 * OptHub REST API
 * OptHub Public REST API.
 *
 * The version of the OpenAPI document: 0.3.0
 * Contact: competition@opthub.ai
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.21.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "opthub_api_client/model/CreateMatchTrial_400_response.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

CreateMatchTrial_400_response::CreateMatchTrial_400_response()
{
    m_CodeIsSet = false;
    m_Message = utility::conversions::to_string_t("");
    m_MessageIsSet = false;
}

CreateMatchTrial_400_response::~CreateMatchTrial_400_response()
{
}

void CreateMatchTrial_400_response::validate()
{
    // TODO: implement validation
}

web::json::value CreateMatchTrial_400_response::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_CodeIsSet)
    {
        
        utility::string_t refVal = fromCodeEnum(m_Code);
        val[utility::conversions::to_string_t(_XPLATSTR("code"))] = ModelBase::toJson(refVal);
        
    }
    if(m_MessageIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("message"))] = ModelBase::toJson(m_Message);
    }

    return val;
}

bool CreateMatchTrial_400_response::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("code"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("code")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setCode;
            ok &= ModelBase::fromJson(fieldValue, refVal_setCode);
            
            setCode(toCodeEnum(refVal_setCode));
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("message"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("message")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setMessage;
            ok &= ModelBase::fromJson(fieldValue, refVal_setMessage);
            setMessage(refVal_setMessage);
            
        }
    }
    return ok;
}

void CreateMatchTrial_400_response::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_CodeIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("code")), fromCodeEnum(m_Code)));
    }
    if(m_MessageIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("message")), m_Message));
    }
}

bool CreateMatchTrial_400_response::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("code"))))
    {
        utility::string_t refVal_setCode;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("code"))), refVal_setCode );
        setCode(toCodeEnum(refVal_setCode));
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("message"))))
    {
        utility::string_t refVal_setMessage;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("message"))), refVal_setMessage );
        setMessage(refVal_setMessage);
    }
    return ok;
}

CreateMatchTrial_400_response::CodeEnum CreateMatchTrial_400_response::toCodeEnum(const utility::string_t& value) const
{
    
    if (value == utility::conversions::to_string_t("InvalidBodyFormat")) {
        return CodeEnum::INVALIDBODYFORMAT;
    }
    
    if (value == utility::conversions::to_string_t("InvalidParameters")) {
        return CodeEnum::INVALIDPARAMETERS;
    }
    
    throw std::invalid_argument("Invalid value for conversion to CodeEnum");
}


const utility::string_t CreateMatchTrial_400_response::fromCodeEnum(const CodeEnum value) const
{
    switch(value)
    {
        
        case CodeEnum::INVALIDBODYFORMAT: return utility::conversions::to_string_t("InvalidBodyFormat");
        
        case CodeEnum::INVALIDPARAMETERS: return utility::conversions::to_string_t("InvalidParameters");
        
    }
}


CreateMatchTrial_400_response::CodeEnum CreateMatchTrial_400_response::getCode() const
{
    return m_Code;
}


void CreateMatchTrial_400_response::setCode(const CodeEnum value)
{
    m_Code = value;
    m_CodeIsSet = true;
}

bool CreateMatchTrial_400_response::codeIsSet() const
{
    return m_CodeIsSet;
}

void CreateMatchTrial_400_response::unsetCode()
{
    m_CodeIsSet = false;
}
utility::string_t CreateMatchTrial_400_response::getMessage() const
{
    return m_Message;
}


void CreateMatchTrial_400_response::setMessage(const utility::string_t& value)
{
    m_Message = value;
    m_MessageIsSet = true;
}

bool CreateMatchTrial_400_response::messageIsSet() const
{
    return m_MessageIsSet;
}

void CreateMatchTrial_400_response::unsetMessage()
{
    m_MessageIsSet = false;
}

}
}
}
}


