/**
 * OptHub REST API
 * OptHub Public REST API.
 *
 * The version of the OpenAPI document: 0.3.0
 * Contact: competition@opthub.ai
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.21.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "opthub_api_client/model/MatchTrialStatus.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

namespace
{
using EnumUnderlyingType = utility::string_t;

MatchTrialStatus::eMatchTrialStatus toEnum(const EnumUnderlyingType& val)
{
    if (val == utility::conversions::to_string_t(_XPLATSTR("evaluating")))
        return MatchTrialStatus::eMatchTrialStatus::EVALUATING;
    if (val == utility::conversions::to_string_t(_XPLATSTR("evaluator_failed")))
        return MatchTrialStatus::eMatchTrialStatus::EVALUATOR_FAILED;
    if (val == utility::conversions::to_string_t(_XPLATSTR("scorer_failed")))
        return MatchTrialStatus::eMatchTrialStatus::SCORER_FAILED;
    if (val == utility::conversions::to_string_t(_XPLATSTR("scoring")))
        return MatchTrialStatus::eMatchTrialStatus::SCORING;
    if (val == utility::conversions::to_string_t(_XPLATSTR("success")))
        return MatchTrialStatus::eMatchTrialStatus::SUCCESS;
    return {};
}

EnumUnderlyingType fromEnum(MatchTrialStatus::eMatchTrialStatus e)
{
    switch (e)
    {
    case MatchTrialStatus::eMatchTrialStatus::EVALUATING:
        return _XPLATSTR("evaluating");
    case MatchTrialStatus::eMatchTrialStatus::EVALUATOR_FAILED:
        return _XPLATSTR("evaluator_failed");
    case MatchTrialStatus::eMatchTrialStatus::SCORER_FAILED:
        return _XPLATSTR("scorer_failed");
    case MatchTrialStatus::eMatchTrialStatus::SCORING:
        return _XPLATSTR("scoring");
    case MatchTrialStatus::eMatchTrialStatus::SUCCESS:
        return _XPLATSTR("success");
    default:
        break;
    }
    return {};
}
}

MatchTrialStatus::MatchTrialStatus()
{
}

MatchTrialStatus::~MatchTrialStatus()
{
}

void MatchTrialStatus::validate()
{
    // TODO: implement validation
}

web::json::value MatchTrialStatus::toJson() const
{
    auto val = fromEnum(m_value);
    return web::json::value(val);
}

bool MatchTrialStatus::fromJson(const web::json::value& val)
{
    m_value = toEnum(val.as_string());
    return true;
}

void MatchTrialStatus::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if (!namePrefix.empty() && namePrefix.back() != _XPLATSTR('.'))
    {
        namePrefix.push_back(_XPLATSTR('.'));
    }

    auto e = fromEnum(m_value);
    multipart->add(ModelBase::toHttpContent(namePrefix, e));
}

bool MatchTrialStatus::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if (!namePrefix.empty() && namePrefix.back() != _XPLATSTR('.'))
    {
        namePrefix.push_back(_XPLATSTR('.'));
    }
    {
        EnumUnderlyingType e;
        ok = ModelBase::fromHttpContent(multipart->getContent(namePrefix), e);
        if (ok)
        {
            auto v = toEnum(e);
            setValue(v);
        }
    }
    return ok;
}

MatchTrialStatus::eMatchTrialStatus MatchTrialStatus::getValue() const
{
   return m_value;
}

void MatchTrialStatus::setValue(MatchTrialStatus::eMatchTrialStatus const value)
{
   m_value = value;
}

MatchTrialStatus::MatchTrialStatus(utility::string_t str){
    setValue( strToEnumMap[str] );
}

}
}
}
}


