/**
 * OptHub REST API
 * OptHub Public REST API.
 *
 * The version of the OpenAPI document: 0.3.0
 * Contact: competition@opthub.ai
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.21.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "opthub_api_client/model/RunnerStatus.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

namespace
{
using EnumUnderlyingType = utility::string_t;

RunnerStatus::eRunnerStatus toEnum(const EnumUnderlyingType& val)
{
    if (val == utility::conversions::to_string_t(_XPLATSTR("Success")))
        return RunnerStatus::eRunnerStatus::SUCCESS;
    if (val == utility::conversions::to_string_t(_XPLATSTR("Failed")))
        return RunnerStatus::eRunnerStatus::FAILED;
    return {};
}

EnumUnderlyingType fromEnum(RunnerStatus::eRunnerStatus e)
{
    switch (e)
    {
    case RunnerStatus::eRunnerStatus::SUCCESS:
        return _XPLATSTR("Success");
    case RunnerStatus::eRunnerStatus::FAILED:
        return _XPLATSTR("Failed");
    default:
        break;
    }
    return {};
}
}

RunnerStatus::RunnerStatus()
{
}

RunnerStatus::~RunnerStatus()
{
}

void RunnerStatus::validate()
{
    // TODO: implement validation
}

web::json::value RunnerStatus::toJson() const
{
    auto val = fromEnum(m_value);
    return web::json::value(val);
}

bool RunnerStatus::fromJson(const web::json::value& val)
{
    m_value = toEnum(val.as_string());
    return true;
}

void RunnerStatus::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if (!namePrefix.empty() && namePrefix.back() != _XPLATSTR('.'))
    {
        namePrefix.push_back(_XPLATSTR('.'));
    }

    auto e = fromEnum(m_value);
    multipart->add(ModelBase::toHttpContent(namePrefix, e));
}

bool RunnerStatus::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if (!namePrefix.empty() && namePrefix.back() != _XPLATSTR('.'))
    {
        namePrefix.push_back(_XPLATSTR('.'));
    }
    {
        EnumUnderlyingType e;
        ok = ModelBase::fromHttpContent(multipart->getContent(namePrefix), e);
        if (ok)
        {
            auto v = toEnum(e);
            setValue(v);
        }
    }
    return ok;
}

RunnerStatus::eRunnerStatus RunnerStatus::getValue() const
{
   return m_value;
}

void RunnerStatus::setValue(RunnerStatus::eRunnerStatus const value)
{
   m_value = value;
}

RunnerStatus::RunnerStatus(utility::string_t str){
    setValue( strToEnumMap[str] );
}

}
}
}
}


