/**
 * OptHub REST API
 * OptHub Public REST API.
 *
 * The version of the OpenAPI document: 0.3.0
 * Contact: competition@opthub.ai
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.21.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "opthub_api_client/model/ServerErrorCode.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

namespace
{
using EnumUnderlyingType = utility::string_t;

ServerErrorCode::eServerErrorCode toEnum(const EnumUnderlyingType& val)
{
    if (val == utility::conversions::to_string_t(_XPLATSTR("UnexpectedServerError")))
        return ServerErrorCode::eServerErrorCode::UNEXPECTEDSERVERERROR;
    return {};
}

EnumUnderlyingType fromEnum(ServerErrorCode::eServerErrorCode e)
{
    switch (e)
    {
    case ServerErrorCode::eServerErrorCode::UNEXPECTEDSERVERERROR:
        return _XPLATSTR("UnexpectedServerError");
    default:
        break;
    }
    return {};
}
}

ServerErrorCode::ServerErrorCode()
{
}

ServerErrorCode::~ServerErrorCode()
{
}

void ServerErrorCode::validate()
{
    // TODO: implement validation
}

web::json::value ServerErrorCode::toJson() const
{
    auto val = fromEnum(m_value);
    return web::json::value(val);
}

bool ServerErrorCode::fromJson(const web::json::value& val)
{
    m_value = toEnum(val.as_string());
    return true;
}

void ServerErrorCode::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if (!namePrefix.empty() && namePrefix.back() != _XPLATSTR('.'))
    {
        namePrefix.push_back(_XPLATSTR('.'));
    }

    auto e = fromEnum(m_value);
    multipart->add(ModelBase::toHttpContent(namePrefix, e));
}

bool ServerErrorCode::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if (!namePrefix.empty() && namePrefix.back() != _XPLATSTR('.'))
    {
        namePrefix.push_back(_XPLATSTR('.'));
    }
    {
        EnumUnderlyingType e;
        ok = ModelBase::fromHttpContent(multipart->getContent(namePrefix), e);
        if (ok)
        {
            auto v = toEnum(e);
            setValue(v);
        }
    }
    return ok;
}

ServerErrorCode::eServerErrorCode ServerErrorCode::getValue() const
{
   return m_value;
}

void ServerErrorCode::setValue(ServerErrorCode::eServerErrorCode const value)
{
   m_value = value;
}

ServerErrorCode::ServerErrorCode(utility::string_t str){
    setValue( strToEnumMap[str] );
}

}
}
}
}


