/**
 * OptHub REST API
 * OptHub Public REST API.
 *
 * The version of the OpenAPI document: 0.3.0
 * Contact: competition@opthub.ai
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.21.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * AuthErrorCode.h
 *
 * Authentication error code
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_AuthErrorCode_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_AuthErrorCode_H_

#include <boost/optional.hpp>

#include "opthub_api_client/ModelBase.h"


namespace org {
namespace openapitools {
namespace client {
namespace model {


class  AuthErrorCode
    : public ModelBase
{
public:
    AuthErrorCode();
    AuthErrorCode(utility::string_t str);
    operator utility::string_t() const {
        return enumToStrMap.at(getValue());
    }


    virtual ~AuthErrorCode();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    enum class eAuthErrorCode
    {
        APIKEYMISSING,
        INVALIDAPIKEY,
    };

    eAuthErrorCode getValue() const;
    void setValue(eAuthErrorCode const value);

    protected:
        eAuthErrorCode m_value;
        std::map<eAuthErrorCode,utility::string_t> enumToStrMap = {
        { eAuthErrorCode::APIKEYMISSING, _XPLATSTR("APIKEYMISSING") },
        { eAuthErrorCode::INVALIDAPIKEY, _XPLATSTR("INVALIDAPIKEY") }
};
        std::map<utility::string_t,eAuthErrorCode> strToEnumMap = {
        { _XPLATSTR("APIKEYMISSING"), eAuthErrorCode::APIKEYMISSING },
        { _XPLATSTR("INVALIDAPIKEY"), eAuthErrorCode::INVALIDAPIKEY }
};

};

}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_AuthErrorCode_H_ */
