/**
 * OptHub REST API
 * OptHub Public REST API.
 *
 * The version of the OpenAPI document: 0.3.0
 * Contact: competition@opthub.ai
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.21.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * MatchTrialStatus.h
 *
 * Types of trial status.
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_MatchTrialStatus_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_MatchTrialStatus_H_

#include <boost/optional.hpp>

#include "opthub_api_client/ModelBase.h"


namespace org {
namespace openapitools {
namespace client {
namespace model {


class  MatchTrialStatus
    : public ModelBase
{
public:
    MatchTrialStatus();
    MatchTrialStatus(utility::string_t str);
    operator utility::string_t() const {
        return enumToStrMap.at(getValue());
    }


    virtual ~MatchTrialStatus();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    enum class eMatchTrialStatus
    {
        EVALUATING,
        EVALUATOR_FAILED,
        SCORER_FAILED,
        SCORING,
        SUCCESS,
    };

    eMatchTrialStatus getValue() const;
    void setValue(eMatchTrialStatus const value);

    protected:
        eMatchTrialStatus m_value;
        std::map<eMatchTrialStatus,utility::string_t> enumToStrMap = {
        { eMatchTrialStatus::EVALUATING, _XPLATSTR("EVALUATING") },
        { eMatchTrialStatus::EVALUATOR_FAILED, _XPLATSTR("EVALUATOR_FAILED") },
        { eMatchTrialStatus::SCORER_FAILED, _XPLATSTR("SCORER_FAILED") },
        { eMatchTrialStatus::SCORING, _XPLATSTR("SCORING") },
        { eMatchTrialStatus::SUCCESS, _XPLATSTR("SUCCESS") }
};
        std::map<utility::string_t,eMatchTrialStatus> strToEnumMap = {
        { _XPLATSTR("EVALUATING"), eMatchTrialStatus::EVALUATING },
        { _XPLATSTR("EVALUATOR_FAILED"), eMatchTrialStatus::EVALUATOR_FAILED },
        { _XPLATSTR("SCORER_FAILED"), eMatchTrialStatus::SCORER_FAILED },
        { _XPLATSTR("SCORING"), eMatchTrialStatus::SCORING },
        { _XPLATSTR("SUCCESS"), eMatchTrialStatus::SUCCESS }
};

};

}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_MatchTrialStatus_H_ */
