/**
 * OptHub REST API
 * OptHub Public REST API.
 *
 * The version of the OpenAPI document: 0.3.0
 * Contact: competition@opthub.ai
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.21.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * ServerErrorCode.h
 *
 * Internal server error code
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_ServerErrorCode_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_ServerErrorCode_H_

#include <boost/optional.hpp>

#include "opthub_api_client/ModelBase.h"


namespace org {
namespace openapitools {
namespace client {
namespace model {


class  ServerErrorCode
    : public ModelBase
{
public:
    ServerErrorCode();
    ServerErrorCode(utility::string_t str);
    operator utility::string_t() const {
        return enumToStrMap.at(getValue());
    }


    virtual ~ServerErrorCode();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    enum class eServerErrorCode
    {
        UNEXPECTEDSERVERERROR,
    };

    eServerErrorCode getValue() const;
    void setValue(eServerErrorCode const value);

    protected:
        eServerErrorCode m_value;
        std::map<eServerErrorCode,utility::string_t> enumToStrMap = {
        { eServerErrorCode::UNEXPECTEDSERVERERROR, _XPLATSTR("UNEXPECTEDSERVERERROR") }
};
        std::map<utility::string_t,eServerErrorCode> strToEnumMap = {
        { _XPLATSTR("UNEXPECTEDSERVERERROR"), eServerErrorCode::UNEXPECTEDSERVERERROR }
};

};

}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_ServerErrorCode_H_ */
