/**
 * OptHub REST API
 * OptHub Public REST API.
 *
 * The version of the OpenAPI document: 0.3.0
 * Contact: competition@opthub.ai
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.21.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * Solution.h
 *
 * Solution information
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_Solution_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_Solution_H_

#include <boost/optional.hpp>

#include "opthub_api_client/ModelBase.h"

#include "opthub_api_client/model/ScalarOrVector.h"
#include <cpprest/details/basic_types.h>

namespace org {
namespace openapitools {
namespace client {
namespace model {

class ScalarOrVector;


/// <summary>
/// Solution information
/// </summary>
class  Solution
    : public ModelBase
{
public:
    Solution();
    virtual ~Solution();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// Solution members


    std::shared_ptr<ScalarOrVector> getVariable() const;
    bool variableIsSet() const;
    void unsetVariable();
    void setVariable(const std::shared_ptr<ScalarOrVector>& value);

    /// <summary>
    /// Solution submitted date and time
    /// </summary>
    utility::datetime getCreatedAt() const;
    bool createdAtIsSet() const;
    void unsetCreatedAt();
    void setCreatedAt(const utility::datetime& value);


protected:
    std::shared_ptr<ScalarOrVector> m_Variable;
    bool m_VariableIsSet;

    utility::datetime m_CreatedAt;
    bool m_CreatedAtIsSet;

};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_Solution_H_ */
